name: Java CI
on:
  push:
    branches: [ master ] # Triggers when code is pushed to the master branch
  pull_request:
    branches: [ master ] # Triggers when a pull request targets the master branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Retrieve the project code from GitHub
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
      
    - name: Build with Maven (Skipping tests)
      run: mvn clean package -DskipTests 
      
    - name: Run tests with H2
      run: mvn test -Dspring.profiles.active=test
